-- MySQL Script generated by MySQL Workbench
-- Mon Dec  4 06:59:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema team015
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `team015` ;

-- -----------------------------------------------------
-- Schema team015
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `team015` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `team015` ;

-- -----------------------------------------------------
-- Table `team015`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `house_number` VARCHAR(255) NULL DEFAULT NULL,
  `road_name` VARCHAR(255) NULL DEFAULT NULL,
  `city_name` VARCHAR(255) NULL DEFAULT NULL,
  `post_code` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 95
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `house_number` ON `team015`.`address` (`house_number` ASC, `post_code` ASC) VISIBLE;

--------------------------------------------------------------------
INSERT INTO `team015`.`address` (house_number, road_name, city_name, post_code) VALUES
('123', 'Maple Street', 'Springfield', 'SP123'),
('456', 'Oak Avenue', 'Greenwood', 'GW456'),
('789', 'Pine Road', 'Lakewood', 'LK789');

-- -----------------------------------------------------
-- Table `team015`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `forename` VARCHAR(255) NULL DEFAULT NULL,
  `surname` VARCHAR(255) NULL DEFAULT NULL,
  `address_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`address_id`)
    REFERENCES `team015`.`address` (`address_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 151
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `address_id` ON `team015`.`users` (`address_id` ASC) VISIBLE;
-----------------------------------------------------------------------------------
INSERT INTO `team015`.`users` (email, forename, surname, address_id) VALUES
('john.doe@example.com', 'John', 'Doe', 1),
('jane.smith@example.com', 'Jane', 'Smith', 2),
('emily.jones@example.com', 'Emily', 'Jones', 3);



-- -----------------------------------------------------
-- Table `team015`.`bank_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`bank_card` (
  `card_number` VARCHAR(255) NOT NULL,
  `expiry_month` INT NOT NULL,
  `expiry_year` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `security_code` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `card_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`card_number`),
  CONSTRAINT `bank_card_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `team015`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `user_id` ON `team015`.`bank_card` (`user_id` ASC) VISIBLE;
------------------------------------------------------------------------
INSERT INTO `team015`.`bank_card` (card_number, expiry_month, expiry_year, user_id, security_code, first_name, card_name, last_name) VALUES
('1234567890123456', 12, 2025, 1, '123', 'John', 'John Doe', 'Doe'),
('2345678901234567', 6, 2024, 2, '456', 'Jane', 'Jane Smith', 'Smith'),
('3456789012345678', 11, 2023, 3, '789', 'Emily', 'Emily Jones', 'Jones');


-- -----------------------------------------------------
-- Table `team015`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`product` (
  `product_code` VARCHAR(255) NOT NULL,
  `brand_name` VARCHAR(255) NULL DEFAULT NULL,
  `product_name` VARCHAR(255) NULL DEFAULT NULL,
  `retail_price` DECIMAL(10,2) NULL DEFAULT NULL,
  `gauge_type` ENUM('OO_GAUGE', 'TT_GAUGE', 'N_GAUGE') NULL DEFAULT NULL,
  PRIMARY KEY (`product_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
------------------------------------------------------------------------
INSERT INTO `team015`.`product` (product_code, brand_name, product_name, retail_price, gauge_type) VALUES
('M001', 'BrandA', 'Model Train Set A', 199.99, 'OO_GAUGE'),
('M002', 'BrandB', 'Model Train Set B', 249.99, 'TT_GAUGE'),
('M003', 'BrandC', 'Model Train Set C', 299.99, 'N_GAUGE');


-- -----------------------------------------------------
-- Table `team015`.`boxed_set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`boxed_set` (
  `product_code` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`product_code`),
  CONSTRAINT `boxed_set_ibfk_1`
    FOREIGN KEY (`product_code`)
    REFERENCES `team015`.`product` (`product_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
-----------------------------------------------------------
INSERT INTO `team015`.`boxed_set` (product_code) VALUES
('C001'),
('C002'),
('C003');


-- -----------------------------------------------------
-- Table `team015`.`part`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`part` (
  `product_code` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`product_code`),
  CONSTRAINT `part_ibfk_1`
    FOREIGN KEY (`product_code`)
    REFERENCES `team015`.`product` (`product_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
----------------------------------------------------------
INSERT INTO `team015`.`part` (product_code) VALUES
('C001'),
('C002');



-- -----------------------------------------------------
-- Table `team015`.`controller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`controller` (
  `product_code` VARCHAR(255) NOT NULL,
  `controller_type` ENUM('STANDARD_CONTROLLER', 'DCC_CONTROLLER', 'DCC_EDIT_CONTROLLER') NULL DEFAULT NULL,
  `is_digital` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`product_code`),
  CONSTRAINT `controller_ibfk_1`
    FOREIGN KEY (`product_code`)
    REFERENCES `team015`.`part` (`product_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `product_code_UNIQUE` ON `team015`.`controller` (`product_code` ASC) VISIBLE;
-------------------------------------------------------------
INSERT INTO `team015`.`controller` (product_code, controller_type, is_digital) VALUES
('C001', 'STANDARD_CONTROLLER', 0),
('C002', 'DCC_CONTROLLER', 1);


-- -----------------------------------------------------
-- Table `team015`.`hashed_passwords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`hashed_passwords` (
  `user_id` INT NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `hashed_passwords_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `team015`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
---------------------------------------------------------------
INSERT INTO `team015`.`hashed_passwords` (user_id, password_hash) VALUES
(1, 'hashed_password_1'),
(2, 'hashed_password_2'),
(3, 'hashed_password_3');


-- -----------------------------------------------------
-- Table `team015`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`inventory` (
  `product_code` VARCHAR(255) NOT NULL,
  `quantity` INT NULL DEFAULT NULL,
  PRIMARY KEY (`product_code`),
  CONSTRAINT `inventory_ibfk_1`
    FOREIGN KEY (`product_code`)
    REFERENCES `team015`.`product` (`product_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
----------------------------------------------------------
INSERT INTO `team015`.`inventory` (product_code, quantity) VALUES
('P001', 10),
('P002', 15),
('P003', 5);

-- -----------------------------------------------------
-- Table `team015`.`locomotive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`locomotive` (
  `product_code` VARCHAR(255) NOT NULL,
  `dcc_type` ENUM('ANALOGUE', 'DCC_READY', 'DCC_FITTED', 'DCC_SOUND') NULL DEFAULT NULL,
  `era` ENUM('ERA_1', 'ERA_2', 'ERA_3', 'ERA_4', 'ERA_5', 'ERA_6', 'ERA_8', 'ERA_7', 'ERA_9', 'ERA_10', 'ERA_11', 'ERA_12') NULL DEFAULT NULL,
  PRIMARY KEY (`product_code`),
  CONSTRAINT `locomotive_ibfk_1`
    FOREIGN KEY (`product_code`)
    REFERENCES `team015`.`part` (`product_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `product_code_UNIQUE` ON `team015`.`locomotive` (`product_code` ASC) VISIBLE;
-----------------------------------------------------------
INSERT INTO `team015`.`locomotive` (product_code, dcc_type, era) VALUES
('L001', 'DCC_READY', 'ERA_4'),
('L002', 'DCC_FITTED', 'ERA_5'),
('L003', 'ANALOGUE', 'ERA_3');

-- -----------------------------------------------------
-- Table `team015`.`orderline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`orderline` (
  `product_code` VARCHAR(255) NOT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `linecost` DECIMAL(10,2) NULL DEFAULT NULL,
  `order_number` INT NOT NULL,
  PRIMARY KEY (`product_code`, `order_number`),
  CONSTRAINT `orderline_ibfk_2`
    FOREIGN KEY (`product_code`)
    REFERENCES `team015`.`product` (`product_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
-----------------------------------------------------------
INSERT INTO `team015`.`orderline` (product_code, quantity, linecost, order_number) VALUES
('P001', 2, 399.98, 1001),
('P002', 1, 249.99, 1002),
('P003', 3, 899.97, 1003);


-- -----------------------------------------------------
-- Table `team015`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`orders` (
  `order_number` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `order_status` ENUM('PENDING', 'CONFIRMED', 'FULFILLED', 'REFUSED') NULL DEFAULT NULL,
  PRIMARY KEY (`order_number`),
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `team015`.`users` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 162
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `user_id` ON `team015`.`orders` (`user_id` ASC) VISIBLE;
------------------------------------------------------------------
INSERT INTO `team015`.`orders` (date, user_id, order_status) VALUES
('2023-01-15', 1, 'CONFIRMED'),
('2023-01-20', 2, 'PENDING'),
('2023-01-25', 3, 'FULFILLED');


-- -----------------------------------------------------
-- Table `team015`.`part_boxed_set_association`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`part_boxed_set_association` (
  `part_product_code` VARCHAR(255) NOT NULL,
  `boxed_set_product_code` VARCHAR(255) NOT NULL,
  `quantity` INT NULL DEFAULT NULL,
  PRIMARY KEY (`part_product_code`, `boxed_set_product_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `boxed_set_product_code` ON `team015`.`part_boxed_set_association` (`boxed_set_product_code` ASC) VISIBLE;
---------------------------------------------------------
INSERT INTO `team015`.`part_boxed_set_association` (part_product_code, boxed_set_product_code, quantity) VALUES
('C001', 'P001', 2),
('C002', 'P002', 3),
('C003', 'P003', 1);


-- -----------------------------------------------------
-- Table `team015`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`roles` (
  `role_id` INT NOT NULL,
  `role_name` ENUM('CUSTOMER', 'STAFF', 'MANAGER') NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
------------------------------------------------------------
INSERT INTO `team015`.`roles` (role_id, role_name) VALUES
(1, 'CUSTOMER'),
(2, 'STAFF'),
(3, 'MANAGER');

-- -----------------------------------------------------
-- Table `team015`.`rolling_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`rolling_stock` (
  `product_code` VARCHAR(255) NOT NULL,
  `rolling_stock_type` ENUM('CARRIAGE', 'WAGON') NOT NULL,
  `era` ENUM('ERA_1', 'ERA_2', 'ERA_3', 'ERA_4', 'ERA_5', 'ERA_6', 'ERA_7', 'ERA_8', 'ERA_9', 'ERA_10', 'ERA_11', 'ERA_12') NOT NULL,
  PRIMARY KEY (`product_code`),
  CONSTRAINT `rolling_stock_ibfk_1`
    FOREIGN KEY (`product_code`)
    REFERENCES `team015`.`part` (`product_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
------------------------------------------------------------
INSERT INTO `team015`.`rolling_stock` (product_code, rolling_stock_type, era) VALUES
('S001', 'CARRIAGE', 'ERA_4'),
('S002', 'WAGON', 'ERA_5'),
('S003', 'CARRIAGE', 'ERA_6');


-- -----------------------------------------------------
-- Table `team015`.`track`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`track` (
  `product_code` VARCHAR(255) NOT NULL,
  `track_type` ENUM('STRAIGHT', 'CURVE', 'POINT', 'CROSSOVER') NULL DEFAULT NULL,
  PRIMARY KEY (`product_code`),
  CONSTRAINT `track_ibfk_1`
    FOREIGN KEY (`product_code`)
    REFERENCES `team015`.`part` (`product_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `product_code_UNIQUE` ON `team015`.`track` (`product_code` ASC) VISIBLE;
--------------------------------------------------------------
INSERT INTO `team015`.`track` (product_code, track_type) VALUES
('R001', 'STRAIGHT'),
('R002', 'CURVE'),
('R003', 'POINT'),
('R004', 'CROSSOVER');


-- -----------------------------------------------------
-- Table `team015`.`track_pack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`track_pack` (
  `product_code` VARCHAR(7) NOT NULL,
  `pack_type` ENUM('STARTER_OVAL', 'EXTENSION_PACK') NULL DEFAULT NULL,
  PRIMARY KEY (`product_code`),
  CONSTRAINT `track_pack_ibfk_1`
    FOREIGN KEY (`product_code`)
    REFERENCES `team015`.`boxed_set` (`product_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `product_code_UNIQUE` ON `team015`.`track_pack` (`product_code` ASC) VISIBLE;
------------------------------------------------------------
INSERT INTO `team015`.`track_pack` (product_code, pack_type) VALUES
('P001', 'STARTER_OVAL'),
('P002', 'EXTENSION_PACK');


-- -----------------------------------------------------
-- Table `team015`.`train_set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`train_set` (
  `product_code` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`product_code`),
  CONSTRAINT `train_set_ibfk_1`
    FOREIGN KEY (`product_code`)
    REFERENCES `team015`.`boxed_set` (`product_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `product_code_UNIQUE` ON `team015`.`train_set` (`product_code` ASC) VISIBLE;
---------------------------------------------------------
INSERT INTO `team015`.`train_set` (product_code) VALUES
('M001'),
('M002'),
('M003');


-- -----------------------------------------------------
-- Table `team015`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team015`.`user_roles` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  CONSTRAINT `user_roles_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `team015`.`users` (`user_id`),
  CONSTRAINT `user_roles_ibfk_2`
    FOREIGN KEY (`role_id`)
    REFERENCES `team015`.`roles` (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `role_id` ON `team015`.`user_roles` (`role_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
--------------------------------------------------------------
INSERT INTO `team015`.`user_roles` (user_id, role_id) VALUES
(1, 1),  -- customer
(2, 2),  -- staff
(3, 3);  -- manager

