package main.java.com.system.model.product.enums;
public enum CarriageType {
	CORRIDOR_FIRST,
	OPEN_FIRST,
	CORRIDOR_SECOND,
	SLEEPER_CAR,
	RESTAURANT_CAR,
	BUFFET_CAR,
	COMPOSITE_COACH,
	GENERAL_UTILITY_VAN,
	OPEN_SECOND,
	POST_OFFICE_SORTING_VAN,
	BRAKE_VAN,
	BRAKE_SECOND,
	COMPOSITE_BRAKE_VAN,
	PULLMAN,
	STANDARD_CALSS;

}