package com.system.model.product.enums;
public enum WagonType {

	CATTLE_WAGON,
	HORSE_BOX_WAGON,
	PARCELS_VAN,
	MINERAL_WAGON_16T,
	COAL_WAGON_6PLANK,
	COAL_WAGON_8PLANK,
	HOPPER_WAGON_20T,
	CLAM_BALLAST_WAGON_102T,
	URCHIN_BOGIE_OPEN_WAGON,
	COALFISH_OPEN_WAGON,
	BOGIE_BOLSTER_WAGON,
	BRAKE_VAN_20T,
	GWR_TOAD_GUARDS_VAN;

}