/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package project.gui;

import java.sql.*;

import javax.swing.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import project.dao.*;
import project.daoimpl.*;
import project.model.product.*;
import project.model.product.abstractproduct.Part;
import project.model.product.association.PartBoxedSetAssociation;
import project.model.product.enums.*;
import project.service.InventoryService;
import project.service.MySqlService;

/**
 *
 * @author thoma
 */
public class NewProduct extends javax.swing.JFrame {


    private InventoryDao inventoryDao = new InventoryDaoImpl();

    private List<String> trainSetPartCodes = new ArrayList<>();
    private List<String> trackPackPartCodes = new ArrayList<>();
    private List<Integer> trainSetPartQuantities = new ArrayList<>();
    private List<Integer> trackPackPartQuantities = new ArrayList<>();

    /**
     * Creates new customizer NewProduct
     */
    public NewProduct() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jComboBox9 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnAddTrainSet = new javax.swing.JButton();
        addTrainSetPartPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtTrainSetPartProductCode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        trainSetPartQuantity = new javax.swing.JSpinner();
        btnAddTrainSetPartPanel = new javax.swing.JButton();
        addTrainSetPartFieldPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnAddTrackPack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        btnAddTrackPackPartPanel = new javax.swing.JButton();
        trackPackPartPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtTrackPackProductCode = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        trackPackPartQuantity = new javax.swing.JSpinner();
        addTrackPackPartFieldPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        priceVal = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        quantityVal = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        jPanel1.setBackground(new java.awt.Color(0, 105, 0));

        jPanel2.setToolTipText("");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ANALOGUE", "DCC_READY", "DCC_FITTED", "DCC_SOUND" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ERA_1", "ERA_2", "ERA_3", "ERA_4", "ERA_5", "ERA_6", "ERA_8", "ERA_7", "ERA_9", "ERA_10", "ERA_11", "ERA_12" }));

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton3ActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Locomotive", jPanel2);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STANDARD_CONTROLLER", "DCC_CONTROLLER", "DCC_EDIT_CONTROLLER" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton5ActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Controller", jPanel3);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STRAIGHT", "CURVE", "POINT", "CROSSOVER" }));

        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton6ActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Track", jPanel5);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ERA_1", "ERA_2", "ERA_3", "ERA_4", "ERA_5", "ERA_6", "ERA_8", "ERA_7", "ERA_9", "ERA_10", "ERA_11", "ERA_12" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARRIAGE", "WAGON" }));

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton4ActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Rolling Stock", jPanel6);

        btnAddTrainSet.setBackground(new java.awt.Color(0, 102, 0));
        btnAddTrainSet.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTrainSet.setText("Add product");
        btnAddTrainSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnAddTrainSetActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        addTrainSetPartPanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setText("Part product code: ");

        jLabel11.setText("Part quantity: ");

        trainSetPartQuantity.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));

        javax.swing.GroupLayout addTrainSetPartPanelLayout = new javax.swing.GroupLayout(addTrainSetPartPanel);
        addTrainSetPartPanel.setLayout(addTrainSetPartPanelLayout);
        addTrainSetPartPanelLayout.setHorizontalGroup(
            addTrainSetPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTrainSetPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addTrainSetPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addTrainSetPartPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtTrainSetPartProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addTrainSetPartPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(trainSetPartQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        addTrainSetPartPanelLayout.setVerticalGroup(
            addTrainSetPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTrainSetPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addTrainSetPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTrainSetPartProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addTrainSetPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(trainSetPartQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAddTrainSetPartPanel.setText("Add more part");
        btnAddTrainSetPartPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTrainSetPartPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addTrainSetPartFieldPanelLayout = new javax.swing.GroupLayout(addTrainSetPartFieldPanel);
        addTrainSetPartFieldPanel.setLayout(addTrainSetPartFieldPanelLayout);
        addTrainSetPartFieldPanelLayout.setHorizontalGroup(
            addTrainSetPartFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        addTrainSetPartFieldPanelLayout.setVerticalGroup(
            addTrainSetPartFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnAddTrainSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddTrainSetPartPanel)
                        .addGap(60, 60, 60))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(addTrainSetPartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addTrainSetPartFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(addTrainSetPartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTrainSetPartFieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTrainSet)
                    .addComponent(btnAddTrainSetPartPanel))
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Train sets", jPanel7);

        btnAddTrackPack.setBackground(new java.awt.Color(0, 102, 0));
        btnAddTrackPack.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTrackPack.setText("Add product");
        btnAddTrackPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnAddTrackPackActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jLabel7.setText("Pack:");

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STARTER_OVAL", "EXTENSION_PACK" }));

        btnAddTrackPackPartPanel.setText("Add more part");
        btnAddTrackPackPartPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTrackPackPartPanelActionPerformed(evt);
            }
        });

        trackPackPartPanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setText("Part product code: ");

        jLabel13.setText("Part quantity: ");

        trackPackPartQuantity.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));

        javax.swing.GroupLayout trackPackPartPanelLayout = new javax.swing.GroupLayout(trackPackPartPanel);
        trackPackPartPanel.setLayout(trackPackPartPanelLayout);
        trackPackPartPanelLayout.setHorizontalGroup(
            trackPackPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trackPackPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(trackPackPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(trackPackPartPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(trackPackPartQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(trackPackPartPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTrackPackProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        trackPackPartPanelLayout.setVerticalGroup(
            trackPackPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trackPackPartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(trackPackPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTrackPackProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(trackPackPartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(trackPackPartQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout addTrackPackPartFieldPanelLayout = new javax.swing.GroupLayout(addTrackPackPartFieldPanel);
        addTrackPackPartFieldPanel.setLayout(addTrackPackPartFieldPanelLayout);
        addTrackPackPartFieldPanelLayout.setHorizontalGroup(
            addTrackPackPartFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        addTrackPackPartFieldPanelLayout.setVerticalGroup(
            addTrackPackPartFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(btnAddTrackPack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddTrackPackPartPanel))
                            .addComponent(trackPackPartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(addTrackPackPartFieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(trackPackPartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addTrackPackPartFieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTrackPack)
                    .addComponent(btnAddTrackPackPartPanel))
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Track Pack", jPanel8);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("General Details");

        jLabel2.setText("Brand");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LMS", "LNER", "GWR" }));

        jLabel3.setText("Name");

        jLabel4.setText("Gauge");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OO_GAUGE", "TT_GAUGE", "N_GAUGE" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Price");

        priceVal.setModel((new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1)));

            jButton1.setText("Cancel");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            quantityVal.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));

            jLabel6.setText("Quantity");

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(89, 89, 89)
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priceVal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(quantityVal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))))
                    .addContainerGap())
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel3)
                    .addGap(3, 3, 3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel4)
                    .addGap(18, 18, 18)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(priceVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quantityVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGap(29, 29, 29))
            );

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(55, 55, 55)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(158, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGap(16, 16, 16))
            );

            jTabbedPane1.getAccessibleContext().setAccessibleName("General");

            getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void cancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel
        this.dispose();
    }//GEN-LAST:event_cancel

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        addCarriageGUI();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        addRailGUI();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButton3ActionPerformed
        addLocomotiveGUI();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        addControllerGUI();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnAddTrainSetActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_btnAddTrainSetActionPerformed
        TrainSetDaoImpl TrainSetDao = new TrainSetDaoImpl();
        ProductDaoImpl productDao = new ProductDaoImpl();

        if (isAnyFieldEmpty(jTextField1, txtTrainSetPartProductCode)) {
            JOptionPane.showMessageDialog(null, "Please enter a valid inputs",
                    "Invalid", JOptionPane.ERROR_MESSAGE);
        } else {

            if (isSetsOrParts(txtTrainSetPartProductCode.getText())) {
                JOptionPane.showMessageDialog(null, "Can not add a set or a pack!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            } else if (!productDao.checkProductCodeExists(txtTrainSetPartProductCode.getText())) {
                JOptionPane.showMessageDialog(null, "Can not find the part. Please check if the correct product code has been entered",
                        "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                // Assuming jSpinner1.getValue() returns a BigDecimal
                int intValue = (Integer) priceVal.getValue();
                int quantity = (Integer) quantityVal.getValue();

                BigDecimal retailPrice = new BigDecimal(intValue);

                // Assuming jComboBox1, jComboBox3, and jComboBox4 return the selected items as Strings
                String gaugeType = jComboBox2.getSelectedItem().toString();
                String productCode = MySqlService.generateProductCode("TRACK_PACK");

                // Create a Locomotive object
                TrainSet trainSet = new TrainSet(
                        productCode,
                        jComboBox1.getSelectedItem().toString(),
                        jTextField1.getText(),
                        retailPrice,
                        Gauge.valueOf(gaugeType)
                );

//        getTrainSetPartQuantity();
                String partProductCode = txtTrainSetPartProductCode.getText();
                int partQuantity = (Integer) trainSetPartQuantity.getValue();
                System.out.println(partProductCode);
                addTrainSetPart(partProductCode, partQuantity, trainSet);
                int i = 0;
                for (String partCode : trainSetPartCodes) {
                    addTrainSetPart(partCode, trainSetPartQuantities.get(i), trainSet);
                    i++;
                }
                TrainSetDao.addTrainSet(trainSet);
                JOptionPane.showMessageDialog(null, "Product successfully added",
                        "Saved", JOptionPane.INFORMATION_MESSAGE);
                inventoryDao.addInventory(productCode, quantity);
            }
        }
    }//GEN-LAST:event_btnAddTrainSetActionPerformed

    private void btnAddTrackPackActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_btnAddTrackPackActionPerformed
        TrackPackDaoImpl TrackPackDao = new TrackPackDaoImpl();
        ProductDaoImpl productDao = new ProductDaoImpl();


        if (isAnyFieldEmpty(jTextField1, txtTrackPackProductCode)) {
            JOptionPane.showMessageDialog(null, "Please enter a valid inputs",
                    "Invalid", JOptionPane.ERROR_MESSAGE);
        } else {

            if (isSetsOrParts(txtTrackPackProductCode.getText())) {
                JOptionPane.showMessageDialog(null, "Can not add a set or a pack!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            } else if (!productDao.checkProductCodeExists(txtTrackPackProductCode.getText())) {
                JOptionPane.showMessageDialog(null, "Can not find the part. Please check if the correct product code has been entered",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
            else {
                // Assuming jSpinner1.getValue() returns a BigDecimal
                int intValue = (Integer) priceVal.getValue();
                int quantity = (Integer) quantityVal.getValue();

                BigDecimal retailPrice = new BigDecimal(intValue);

                // Assuming jComboBox1, jComboBox3, and jComboBox4 return the selected items as Strings
                String gaugeType = jComboBox2.getSelectedItem().toString();
                String packType = jComboBox10.getSelectedItem().toString();
                String productCode = MySqlService.generateProductCode("TRACK_PACK");

                // Create a Locomotive object
                TrackPack trackPack = new TrackPack(
                        productCode,
                        jComboBox1.getSelectedItem().toString(),
                        jTextField1.getText(),
                        retailPrice,
                        Gauge.valueOf(gaugeType),
                        TrackPackType.valueOf(packType)
                );
                //Add Parts
                String partProductCode = txtTrackPackProductCode.getText();
                int partQuantity = (Integer) trackPackPartQuantity.getValue();
                System.out.println(partProductCode);
                addTrackPackPart(partProductCode, partQuantity, trackPack);
//        getTrackPackPartQuantity();
                int i = 0;
                for (String partCode : trackPackPartCodes) {
                    addTrackPackPart(partCode, trackPackPartQuantities.get(i), trackPack);
                    i++;
                }

                TrackPackDao.addTrackPack(trackPack);
                JOptionPane.showMessageDialog(null, "Product successfully added",
                        "Saved", JOptionPane.INFORMATION_MESSAGE);
                inventoryDao.addInventory(productCode, quantity);
            }
        }
    }//GEN-LAST:event_btnAddTrackPackActionPerformed

    private void btnAddTrainSetPartPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTrainSetPartPanelActionPerformed
        // TODO add your handling code here:
        ProductDaoImpl productDao = new ProductDaoImpl();
        if (!productDao.checkProductCodeExists(txtTrainSetPartProductCode.getText())){
            JOptionPane.showMessageDialog(null, "Can not find the part. Please check if the correct product code has been entered",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (isSetsOrParts(txtTrainSetPartProductCode.getText())) {
                JOptionPane.showMessageDialog(null, "Can not add a set or a pack!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                trainSetPartCodes.add(txtTrainSetPartProductCode.getText());
                trainSetPartQuantities.add((Integer) trainSetPartQuantity.getValue());
                txtTrainSetPartProductCode.setText("");
                trainSetPartQuantity.setValue(0);
            }
        }
    }//GEN-LAST:event_btnAddTrainSetPartPanelActionPerformed

    private void btnAddTrackPackPartPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTrackPackPartPanelActionPerformed
        // TODO add your handling code here:
        ProductDaoImpl productDao = new ProductDaoImpl();
        System.out.println(txtTrackPackProductCode.getText());
        if (!productDao.checkProductCodeExists(txtTrackPackProductCode.getText())){
            JOptionPane.showMessageDialog(null, "Can not find the part. Please check if the correct product code has been entered",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (isSetsOrParts(txtTrackPackProductCode.getText())) {
                JOptionPane.showMessageDialog(null, "Can not add a set or a pack!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                System.out.println("Found product");
                trackPackPartCodes.add(txtTrackPackProductCode.getText());
                trackPackPartQuantities.add((Integer) trackPackPartQuantity.getValue());
                txtTrackPackProductCode.setText("");
                trackPackPartQuantity.setValue(0);
            }

        }
    }//GEN-LAST:event_btnAddTrackPackPartPanelActionPerformed

    private void addLocomotiveGUI() throws SQLException {
        LocomotiveDaoImpl locomotiveDao = new LocomotiveDaoImpl();

        if (isAnyFieldEmpty(jTextField1)) {
            JOptionPane.showMessageDialog(null, "Please enter valid inputs",
                    "Invalid", JOptionPane.ERROR_MESSAGE);
        } else {

            // Assuming jSpinner1.getValue() returns a BigDecimal
            int intValue = (Integer) priceVal.getValue();
            int quantity = (Integer) quantityVal.getValue();
            BigDecimal retailPrice = new BigDecimal(intValue);

            // Assuming jComboBox1, jComboBox3, and jComboBox4 return the selected items as Strings
            String gaugeType = jComboBox2.getSelectedItem().toString();
            String dccType = jComboBox3.getSelectedItem().toString();
            String era = jComboBox4.getSelectedItem().toString();
            String productCode = MySqlService.generateProductCode("LOCOMOTIVE");

            // Create a Locomotive object
            Locomotive locomotive = new Locomotive(
                    productCode,
                    jComboBox1.getSelectedItem().toString(),
                    jTextField1.getText(),
                    retailPrice,
                    Gauge.valueOf(gaugeType),
                    DCCType.valueOf(dccType), // Assuming DCCType is an enum
                    Era.valueOf(era) // Assuming Era is an enum
            );

            locomotiveDao.addLocomotive(locomotive);
            JOptionPane.showMessageDialog(null, "Product successfully added",
                    "Saved", JOptionPane.INFORMATION_MESSAGE);
            inventoryDao.addInventory(productCode, quantity);
        }
    }

    private void addControllerGUI() throws SQLException {
        ControllerDaoImpl controllerDao = new ControllerDaoImpl();

        if (isAnyFieldEmpty(jTextField1)) {
            JOptionPane.showMessageDialog(null, "Please enter valid inputs",
                    "Invalid", JOptionPane.ERROR_MESSAGE);
        } else {

            int intValue = (Integer) priceVal.getValue();
            int quantity = (Integer) quantityVal.getValue();
            BigDecimal retailPrice = new BigDecimal(intValue);
            String gaugeType = jComboBox2.getSelectedItem().toString();
            ControllerType controllerType = ControllerType.valueOf(jComboBox7.getSelectedItem().toString());
            Boolean isDigital = Boolean.valueOf(jComboBox9.getSelectedItem().toString());
            String productCode = MySqlService.generateProductCode("CONTROLLER");

            // Create a Controller object
            Controller controller = new Controller(
                    productCode,
                    jComboBox1.getSelectedItem().toString(),
                    jTextField1.getText(),
                    retailPrice,
                    Gauge.valueOf(gaugeType),
                    controllerType,
                    isDigital
            );

            controllerDao.addController(controller);
            JOptionPane.showMessageDialog(null, "Product successfully added",
                    "Saved", JOptionPane.INFORMATION_MESSAGE);
            inventoryDao.addInventory(productCode, quantity);
        }
    }

    private void addRailGUI() throws SQLException {
        TrackDaoImpl trackDao = new TrackDaoImpl();

        if (isAnyFieldEmpty(jTextField1)) {
            JOptionPane.showMessageDialog(null, "Please enter valid inputs",
                    "Invalid", JOptionPane.ERROR_MESSAGE);
        } else {

            int intValue = (Integer) priceVal.getValue();
            int quantity = (Integer) quantityVal.getValue();
            BigDecimal retailPrice = new BigDecimal(intValue);
            String gaugeType = jComboBox2.getSelectedItem().toString();
            String trackType = jComboBox8.getSelectedItem().toString();
            String productCode = MySqlService.generateProductCode("TRACK");

            Track track = new Track(
                    productCode,
                    jComboBox1.getSelectedItem().toString(),
                    jTextField1.getText(),
                    retailPrice,
                    Gauge.valueOf(gaugeType),
                    TrackType.valueOf(trackType)
            );

            trackDao.addTrack(track);
            JOptionPane.showMessageDialog(null, "Product successfully added",
                    "Saved", JOptionPane.INFORMATION_MESSAGE);
            inventoryDao.addInventory(productCode, quantity);
        }
    }

    private void addCarriageGUI() throws SQLException {
        if (isAnyFieldEmpty(jTextField1)) {
            JOptionPane.showMessageDialog(null, "Please enter valid inputs",
                    "Invalid", JOptionPane.ERROR_MESSAGE);
        } else {
            RollingStockDaoImpl rollingStockDao = new RollingStockDaoImpl();

            int intValue = (Integer) priceVal.getValue();
            int quantity = (Integer) quantityVal.getValue();
            BigDecimal retailPrice = new BigDecimal(intValue);
            String gaugeType = jComboBox2.getSelectedItem().toString();
            String rollingStockType = jComboBox6.getSelectedItem().toString();
            String era = jComboBox5.getSelectedItem().toString();
            String productCode = MySqlService.generateProductCode("CARRIAGE");

            RollingStock rollingStock = new RollingStock(
                    productCode,
                    jComboBox1.getSelectedItem().toString(),
                    jTextField1.getText(),
                    retailPrice,
                    Gauge.valueOf(gaugeType),
                    RollingStockType.valueOf(rollingStockType),
                    Era.valueOf(era)
            );

            rollingStockDao.addRollingStock(rollingStock);
            JOptionPane.showMessageDialog(null, "Product successfully added",
                    "Saved", JOptionPane.INFORMATION_MESSAGE);
            inventoryDao.addInventory(productCode, quantity);
        }
    }

//    private void addTrainSetPartPanel() {
//        JPanel addTrainSetPartPanel3 = new javax.swing.JPanel();
//        JLabel jLabel16 = new javax.swing.JLabel();
//        JTextField txtTrainSetPartProductCode3 = new javax.swing.JTextField();
//        JLabel jLabel17 = new javax.swing.JLabel();
//        JSpinner trainSetPartQuantity3 = new javax.swing.JSpinner();
//
//
//        addTrainSetPartPanel3.setBackground(new java.awt.Color(204, 204, 204));
//
//        jLabel16.setText("Part product code: ");
//
//        jLabel17.setText("Part quantity: ");
//
//        trainSetPartQuantity3.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
//
//        javax.swing.GroupLayout addTrainSetPartPanel3Layout = new javax.swing.GroupLayout(addTrainSetPartPanel3);
//        addTrainSetPartPanel3.setLayout(addTrainSetPartPanel3Layout);
//        addTrainSetPartPanel3Layout.setHorizontalGroup(
//                addTrainSetPartPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(addTrainSetPartPanel3Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(addTrainSetPartPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(addTrainSetPartPanel3Layout.createSequentialGroup()
//                                                .addComponent(jLabel16)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(txtTrainSetPartProductCode3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addGroup(addTrainSetPartPanel3Layout.createSequentialGroup()
//                                                .addComponent(jLabel17)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(trainSetPartQuantity3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addContainerGap(51, Short.MAX_VALUE))
//        );
//        addTrainSetPartPanel3Layout.setVerticalGroup(
//                addTrainSetPartPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(addTrainSetPartPanel3Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(addTrainSetPartPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel16)
//                                        .addComponent(txtTrainSetPartProductCode3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addGroup(addTrainSetPartPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jLabel17)
//                                        .addComponent(trainSetPartQuantity3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//
//        javax.swing.GroupLayout addTrainSetPartFieldPanelLayout = new javax.swing.GroupLayout(addTrainSetPartFieldPanel);
//        jPanel1.setLayout(addTrainSetPartFieldPanelLayout);
//        addTrainSetPartFieldPanelLayout.setHorizontalGroup(
//                addTrainSetPartFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(addTrainSetPartFieldPanelLayout.createSequentialGroup()
//                                .addGap(23, 23, 23)
//                                .addComponent(addTrainSetPartPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addContainerGap(809, Short.MAX_VALUE))
//        );
//        addTrainSetPartFieldPanelLayout.setVerticalGroup(
//                addTrainSetPartFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(addTrainSetPartFieldPanelLayout.createSequentialGroup()
//                                .addGap(40, 40, 40)
//                                .addComponent(addTrainSetPartPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addContainerGap(970, Short.MAX_VALUE))
//        );
//
//        trainSetPartCodeFields.add(txtTrainSetPartProductCode3);
//        trainSetPartSpinnerList.add(trainSetPartQuantity3);
//        pack();
//    }

//    private void addTrackPackPartPanel() {
//        JPanel addTrackPackPartPanel3 = new javax.swing.JPanel();
//        JLabel jLabel16 = new javax.swing.JLabel();
//        JTextField txtTrackPackProductCode3 = new javax.swing.JTextField();
//        JLabel jLabel17 = new javax.swing.JLabel();
//        JSpinner trackPackPartQuantity3 = new javax.swing.JSpinner();
//
//
//        addTrackPackPartPanel3.setBackground(new java.awt.Color(204, 204, 204));
//
//        jLabel16.setText("Part product code: ");
//
//        jLabel17.setText("Part quantity: ");
//
//        trackPackPartQuantity3.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
//
//        javax.swing.GroupLayout addTrainSetPartPanel3Layout = new javax.swing.GroupLayout(addTrackPackPartPanel3);
//        addTrackPackPartPanel3.setLayout(addTrainSetPartPanel3Layout);
//        addTrainSetPartPanel3Layout.setHorizontalGroup(
//                addTrainSetPartPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(addTrainSetPartPanel3Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(addTrainSetPartPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(addTrainSetPartPanel3Layout.createSequentialGroup()
//                                                .addComponent(jLabel16)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(txtTrackPackProductCode3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addGroup(addTrainSetPartPanel3Layout.createSequentialGroup()
//                                                .addComponent(jLabel17)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(trackPackPartQuantity3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addContainerGap(51, Short.MAX_VALUE))
//        );
//        addTrainSetPartPanel3Layout.setVerticalGroup(
//                addTrainSetPartPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(addTrainSetPartPanel3Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(addTrainSetPartPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jLabel16)
//                                        .addComponent(txtTrackPackProductCode3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addGroup(addTrainSetPartPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jLabel17)
//                                        .addComponent(trackPackPartQuantity3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//
//        javax.swing.GroupLayout addTrainSetPartFieldPanelLayout = new javax.swing.GroupLayout(addTrainSetPartFieldPanel);
//        jPanel1.setLayout(addTrainSetPartFieldPanelLayout);
//        addTrainSetPartFieldPanelLayout.setHorizontalGroup(
//                addTrainSetPartFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(addTrainSetPartFieldPanelLayout.createSequentialGroup()
//                                .addGap(23, 23, 23)
//                                .addComponent(addTrackPackPartPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addContainerGap(809, Short.MAX_VALUE))
//        );
//        addTrainSetPartFieldPanelLayout.setVerticalGroup(
//                addTrainSetPartFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(addTrainSetPartFieldPanelLayout.createSequentialGroup()
//                                .addGap(40, 40, 40)
//                                .addComponent(addTrackPackPartPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addContainerGap(970, Short.MAX_VALUE))
//        );
//
//        addTrackPackPartFieldPanel.add(txtTrackPackProductCode3);
//        trackPackPartSpinnerList.add(trackPackPartQuantity3);
//        pack();
//    }

//    private void getTrainSetPartQuantity(){
//        int i = 0;
//        for (JSpinner spinner : trainSetPartSpinnerList) {
//            trainSetPartQuantities[i] = (Integer)spinner.getValue();
//            i ++;
//        }
//    }

//    private void getTrackPackPartQuantity(){
//        int i = 0;
//        for (JSpinner spinner : trackPackPartSpinnerList) {
//            trackPackPartQuantities[i] = (Integer)spinner.getValue();
//            i ++;
//        }
//    }

    private void addTrainSetPart(String partCode, int partQuantity, TrainSet trainSet){
        Part part = null;
        char firstChar = partCode.charAt(0);
        switch (firstChar) {
            case 'R':
                TrackDao TrackDao = new TrackDaoImpl();
                part = TrackDao.getTrack(partCode);
                break;

            case 'C':
                ControllerDao ControllerDao = new ControllerDaoImpl();
                part = ControllerDao.getController(partCode);
                break;

            case 'L':
                LocomotiveDao locomotiveDao = new LocomotiveDaoImpl();
                part = locomotiveDao.getLocomotive(partCode);
                break;

            case 'S':
                RollingStockDao RollingStockDao = new RollingStockDaoImpl();
                try {
                    part = RollingStockDao.getRollingStock(partCode);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
                break;
            default:
                throw new IllegalArgumentException("Unknown product type: " + firstChar);
        }
        PartBoxedSetAssociation partBoxedSetAssociation = new PartBoxedSetAssociation(trainSet, part, partQuantity);
        PartBoxedSetAssociationDao partBoxedSetAssociationDao = new PartBoxedSetAssociationDaoImpl();
        partBoxedSetAssociationDao.addAssociation(partBoxedSetAssociation);
    }

    private void addTrackPackPart(String partCode, int partQuantity, TrackPack trackPack){
        Part part = null;
        char firstChar = partCode.charAt(0);
        switch (firstChar) {
            case 'R':
                TrackDao TrackDao = new TrackDaoImpl();
                part = TrackDao.getTrack(partCode);
                break;

            case 'C':
                ControllerDao ControllerDao = new ControllerDaoImpl();
                part = ControllerDao.getController(partCode);
                break;

            case 'L':
                LocomotiveDao locomotiveDao = new LocomotiveDaoImpl();
                part = locomotiveDao.getLocomotive(partCode);
                break;

            case 'S':
                RollingStockDao RollingStockDao = new RollingStockDaoImpl();
                try {
                    part = RollingStockDao.getRollingStock(partCode);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
                break;
            default:
                throw new IllegalArgumentException("Unknown product type: " + firstChar);
        }
        PartBoxedSetAssociation partBoxedSetAssociation = new PartBoxedSetAssociation(trackPack, part, partQuantity);
        PartBoxedSetAssociationDao partBoxedSetAssociationDao = new PartBoxedSetAssociationDaoImpl();
        partBoxedSetAssociationDao.addAssociation(partBoxedSetAssociation);
    }

    private boolean isAnyFieldEmpty(JTextField... fields) {
        for (JTextField field : fields) {
            if (field.getText() == null || field.getText().trim().isEmpty()) {
                return true;
            }
        }
        return false;
    }

    private boolean isSetsOrParts(String code){
        char firstChar = code.charAt(0);
        switch (firstChar) {
            case 'M', 'P':
                return true;
            default:
                return false;
        }
    }


    
                           

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addTrackPackPartFieldPanel;
    private javax.swing.JPanel addTrainSetPartFieldPanel;
    private javax.swing.JPanel addTrainSetPartPanel;
    private javax.swing.JButton btnAddTrackPack;
    private javax.swing.JButton btnAddTrackPackPartPanel;
    private javax.swing.JButton btnAddTrainSet;
    private javax.swing.JButton btnAddTrainSetPartPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JSpinner priceVal;
    private javax.swing.JSpinner quantityVal;
    private javax.swing.JPanel trackPackPartPanel;
    private javax.swing.JSpinner trackPackPartQuantity;
    private javax.swing.JSpinner trainSetPartQuantity;
    private javax.swing.JTextField txtTrackPackProductCode;
    private javax.swing.JTextField txtTrainSetPartProductCode;
    // End of variables declaration//GEN-END:variables
}
