
package project.gui;
import project.dao.*;
import project.daoimpl.*;
import project.model.order.Order;
import project.model.order.OrderLine;
import project.model.product.*;
import project.model.user.User;
import project.service.MysqlService;
import project.utils.UserSessionManager;

import javax.swing.*;
import java.math.BigDecimal;
import java.util.List;

/**
 *
 * @author linyu
 */
public class ProductDetails extends javax.swing.JFrame {

    /**
     * Creates new form Default
     */
    private TrainSet trainSet;

    public ProductDetails(TrainSet trainSet) {
        this.trainSet = trainSet;
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnMyDetails = new javax.swing.JButton();
        btnRecentOrders = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        btnStaffInterface = new javax.swing.JButton();
        btnManagerInterface = new javax.swing.JButton();
        defaultImage = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        brandLabel = new javax.swing.JLabel();
        productCodeLabel = new javax.swing.JLabel();
        btnAddOrderLine = new javax.swing.JButton();
        quantityVal = new javax.swing.JSpinner();
        priceLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        jPopupMenu1.setPreferredSize(new java.awt.Dimension(20, 50));

        jMenuItem1.setText("jMenuItem1");
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Category");
        setPreferredSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 800));

        btnMyDetails.setBackground(new java.awt.Color(0, 102, 0));
        btnMyDetails.setForeground(new java.awt.Color(204, 204, 204));
        btnMyDetails.setText("My Details");
        btnMyDetails.setBorder(null);
        btnMyDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyDetailsActionPerformed(evt);
            }
        });

        btnRecentOrders.setBackground(new java.awt.Color(0, 102, 0));
        btnRecentOrders.setForeground(new java.awt.Color(204, 204, 204));
        btnRecentOrders.setText("Recent Orders");
        btnRecentOrders.setBorder(null);
        btnRecentOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecentOrdersActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(0, 102, 0));
        btnLogOut.setForeground(new java.awt.Color(204, 204, 204));
        btnLogOut.setText("Log out");
        btnLogOut.setBorder(null);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMyDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnRecentOrders))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnMyDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecentOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 664, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(61, 61, 61))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 200, 800);

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Train sets");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 50, 176, 47);

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));

        title.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Product name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(title)
                .addContainerGap(603, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(200, 120, 800, 70);

        btnStaffInterface.setBackground(new java.awt.Color(0, 102, 0));
        btnStaffInterface.setForeground(new java.awt.Color(204, 204, 204));
        btnStaffInterface.setText("Staff interface");
        btnStaffInterface.setBorder(null);
        btnStaffInterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffInterfaceActionPerformed(evt);
            }
        });
        jPanel1.add(btnStaffInterface);
        btnStaffInterface.setBounds(840, 10, 130, 17);

        btnManagerInterface.setBackground(new java.awt.Color(0, 102, 0));
        btnManagerInterface.setForeground(new java.awt.Color(204, 204, 204));
        btnManagerInterface.setText("Manager interface");
        btnManagerInterface.setBorder(null);
        btnManagerInterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerInterfaceActionPerformed(evt);
            }
        });
        jPanel1.add(btnManagerInterface);
        btnManagerInterface.setBounds(840, 50, 150, 17);
        jPanel1.add(defaultImage);
        defaultImage.setBounds(270, 210, 240, 160);

        nameLabel.setText("Name");
        jPanel1.add(nameLabel);
        nameLabel.setBounds(630, 230, 35, 17);

        brandLabel.setText("Brand");
        jPanel1.add(brandLabel);
        brandLabel.setBounds(630, 260, 41, 17);

        productCodeLabel.setText("Type");
        jPanel1.add(productCodeLabel);
        productCodeLabel.setBounds(630, 290, 28, 17);

        btnAddOrderLine.setBackground(new java.awt.Color(0, 102, 0));
        btnAddOrderLine.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnAddOrderLine.setForeground(new java.awt.Color(255, 255, 255));
        btnAddOrderLine.setText("Add to basket");
        btnAddOrderLine.setMaximumSize(new java.awt.Dimension(151, 24));
        btnAddOrderLine.setMinimumSize(new java.awt.Dimension(151, 24));
        btnAddOrderLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderLineActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddOrderLine);
        btnAddOrderLine.setBounds(770, 610, 160, 60);
        jPanel1.add(quantityVal);
        quantityVal.setBounds(780, 560, 110, 30);

        priceLabel.setText("jLabel3");
        jPanel1.add(priceLabel);
        priceLabel.setBounds(630, 320, 41, 17);

        typeLabel.setText("jLabel3");
        jPanel1.add(typeLabel);
        typeLabel.setBounds(630, 350, 41, 17);

        btnBack.setBackground(new java.awt.Color(0, 102, 0));
        btnBack.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back ");
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(630, 613, 120, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Default DefaultFrame = new Default();
        DefaultFrame.setVisible(true);
        DefaultFrame.pack();
        DefaultFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMyDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyDetailsActionPerformed
        // Jump to My Details page:
        MyDetails MyDetailsFrame = new MyDetails();
        MyDetailsFrame.setVisible(true);
        MyDetailsFrame.pack();
        MyDetailsFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnMyDetailsActionPerformed

    private void btnRecentOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecentOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecentOrdersActionPerformed

    private void btnStaffInterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffInterfaceActionPerformed
        StaffDashboard StaffDashboardFrame = new StaffDashboard();
        StaffDashboardFrame.setVisible(true);
        StaffDashboardFrame.pack();
        StaffDashboardFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnStaffInterfaceActionPerformed

    private void btnManagerInterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerInterfaceActionPerformed
        ManagerDashboard ManagerDashboardFrame = new ManagerDashboard();
        ManagerDashboardFrame.setVisible(true);
        ManagerDashboardFrame.pack();
        ManagerDashboardFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnManagerInterfaceActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // log out
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnAddOrderLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderLineActionPerformed
        //Add a product to orderline
        int quantity = (Integer) quantityVal.getValue();
        User currentUser = UserSessionManager.getInstance().getLoggedInUser();
        // TODO If there is already a order, then just add a orderline
        Order order = new Order(currentUser);
        OrderLine orderLine = new OrderLine(trainSet.getProductCode(), quantity, trainSet.getRetailPrice(), order.getOrderNumber());
        MysqlService mysqlService = new MysqlService();
        OrderDao orderDao = new OrderDaoImpl(mysqlService);
        orderDao.addOrderLine(orderLine);
    }//GEN-LAST:event_btnAddOrderLineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brandLabel;
    private javax.swing.JButton btnAddOrderLine;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManagerInterface;
    private javax.swing.JButton btnMyDetails;
    private javax.swing.JButton btnRecentOrders;
    private javax.swing.JButton btnStaffInterface;
    private javax.swing.JLabel defaultImage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel productCodeLabel;
    private javax.swing.JSpinner quantityVal;
    private javax.swing.JLabel title;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
