/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.gui;

import project.dao.OrderDao;
import project.dao.OrderLineDao;
import project.dao.ProductDao;
import project.daoimpl.OrderDaoImpl;
import project.daoimpl.OrderLineDaoImpl;
import project.daoimpl.ProductDaoImpl;
import project.gui.Default;
import project.model.order.Order;
import project.model.order.OrderLine;
import project.model.product.abstractproduct.Product;
import project.model.user.User;
import project.service.MySqlService;
import project.service.OrderService;
import project.utils.UserSessionManager;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 *
 * @author linyu
 */
public class RecentOrders extends javax.swing.JFrame {

    /**
     * Creates new form Default
     */
    public RecentOrders() {
        initComponents();
        loadRecentOrders();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnMyDetails = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Category");
        setPreferredSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 800));

        btnBack.setBackground(new java.awt.Color(0, 102, 0));
        btnBack.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnMyDetails.setBackground(new java.awt.Color(0, 102, 0));
        btnMyDetails.setForeground(new java.awt.Color(204, 204, 204));
        btnMyDetails.setText("My Details");
        btnMyDetails.setBorder(null);
        btnMyDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMyDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnMyDetails)
                .addGap(248, 248, 248)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(474, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 160, 800);

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));

        title.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Recent Orders");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(title)
                .addContainerGap(641, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(160, 0, 840, 70);

        javax.swing.GroupLayout orderContainerLayout = new javax.swing.GroupLayout(orderContainer);
        orderContainer.setLayout(orderContainerLayout);
        orderContainerLayout.setHorizontalGroup(
            orderContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        orderContainerLayout.setVerticalGroup(
            orderContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(orderContainer);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(160, 70, 840, 730);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Default DefaultFrame = new Default();
        DefaultFrame.setVisible(true);
        DefaultFrame.pack();
        DefaultFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMyDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyDetailsActionPerformed
        MyDetails MyDetailsFrame = new MyDetails();
        MyDetailsFrame.setVisible(true);
        MyDetailsFrame.pack();
        MyDetailsFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnMyDetailsActionPerformed

    private void loadRecentOrders(){
        User currentUser = UserSessionManager.getInstance().getLoggedInUser();
        OrderDao orderDao = new OrderDaoImpl();
        OrderService orderService = new OrderService(orderDao);
        OrderLineDao orderLineDao = new OrderLineDaoImpl();
        List<Order> allOrders = orderDao.getOrdersByUserId(currentUser.getUserID());
        orderContainer.setLayout(new BoxLayout(orderContainer, BoxLayout.Y_AXIS));
        orderContainer.add(Box.createVerticalStrut(15));
        //Get recent orders except pending orders
        for (Order order: allOrders) {
            List<OrderLine> allOrderLines = orderLineDao.getAllOrderLines(order.getOrderNumber());
            JPanel orderPanel = new JPanel();
            orderPanel.setLayout(new GridBagLayout());
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridwidth = GridBagConstraints.REMAINDER;
            gbc.anchor = GridBagConstraints.CENTER;
            gbc.insets = new Insets(10,20,10,20);

            JLabel lblStatus = new JLabel("Status: " + order.getOrderStatus().toString());
            JLabel lblDate = new JLabel(order.getDate().toString());
            JLabel lblOrderNum = new JLabel("Order number: " + Integer.toString(order.getOrderNumber()));
            JLabel lblTotalCosts = new JLabel("Total: " + orderService.calculateTotal(order).toString());

            orderPanel.setBackground(new java.awt.Color(24, 150, 62));

            lblStatus.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14));
            lblStatus.setForeground(new java.awt.Color(20, 55, 196));
            lblDate.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12));
            lblOrderNum.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12));
            lblOrderNum.setForeground(new java.awt.Color(160, 160, 160));
            lblTotalCosts.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12));

            orderPanel.add(lblStatus, gbc);
            orderPanel.add(lblDate, gbc);
            orderPanel.add(lblOrderNum, gbc);
            orderPanel.add(lblTotalCosts, gbc);

            //Display ordered products
            for(OrderLine orderLine : allOrderLines){
                ProductDao productDao = new ProductDaoImpl();
                Product product = productDao.getProduct(orderLine.getProductCode());

                //Display the order line
                JPanel productPanel = new JPanel();
                productPanel.setLayout(new GridBagLayout());

                JLabel lblName = new JLabel(product.getProductName());
                JLabel lblPrice = new JLabel("Price: " + product.getRetailPrice() + " £");
                JButton btnViewDetails = new JButton("View details");

                productPanel.setBackground(new java.awt.Color(104, 152, 118));
                lblName.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
                lblName.setForeground(new java.awt.Color(255, 255, 255));
                lblPrice.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
                lblPrice.setForeground(new java.awt.Color(255, 255, 255));

                productPanel.add(lblName,gbc);
                productPanel.add(lblPrice,gbc);
                productPanel.add(btnViewDetails,gbc);

                btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        viewProductDetails(product);
                    }
                });
                orderPanel.add(productPanel,gbc);
            }
            orderContainer.add(orderPanel);
        }
    }

    private void viewProductDetails(Product product){
        ProductDetails ProductDetailsFrame = new ProductDetails(product);
        ProductDetailsFrame.setVisible(true);
        ProductDetailsFrame.pack();
        ProductDetailsFrame.setLocationRelativeTo(null);
        this.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMyDetails;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel orderContainer;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
